#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 125
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 66
#define ALIAS_COUNT 0
#define TOKEN_COUNT 43
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_ident = 1,
  anon_sym_fn = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  sym_num_lit = 5,
  sym_float_lit = 6,
  sym_str_lit = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  anon_sym_PLUS = 10,
  anon_sym_DASH = 11,
  anon_sym_SLASH = 12,
  anon_sym_STAR = 13,
  anon_sym_COMMA = 14,
  anon_sym_EQ_EQ = 15,
  anon_sym_BANG_EQ = 16,
  anon_sym_LT = 17,
  anon_sym_LT_EQ = 18,
  anon_sym_GT = 19,
  anon_sym_GT_EQ = 20,
  anon_sym_PIPE_PIPE = 21,
  anon_sym_AMP_AMP = 22,
  anon_sym_LBRACE = 23,
  anon_sym_RBRACE = 24,
  anon_sym_let = 25,
  anon_sym_EQ = 26,
  anon_sym_SEMI = 27,
  anon_sym_if = 28,
  anon_sym_else = 29,
  anon_sym_for = 30,
  anon_sym_while = 31,
  anon_sym_print = 32,
  anon_sym_return = 33,
  anon_sym_none = 34,
  anon_sym_Int = 35,
  anon_sym_String = 36,
  anon_sym_Float = 37,
  anon_sym_LPAREN_RPAREN = 38,
  anon_sym_extern = 39,
  anon_sym_DASH_GT = 40,
  anon_sym_COLON = 41,
  anon_sym_struct = 42,
  sym_prog = 43,
  sym__items = 44,
  sym_item = 45,
  sym_func_decl = 46,
  sym_lit = 47,
  sym_call = 48,
  sym_expr = 49,
  sym__exprs = 50,
  sym_cond = 51,
  sym_block = 52,
  sym_stat = 53,
  sym_stats = 54,
  sym_type = 55,
  sym_extern = 56,
  sym__return_type = 57,
  sym_func_body = 58,
  sym__type_specifier = 59,
  sym_param = 60,
  sym_param_list = 61,
  sym_field = 62,
  sym_fields = 63,
  sym_struct_decl = 64,
  aux_sym_block_repeat1 = 65,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_num_lit] = "num_lit",
  [sym_float_lit] = "float_lit",
  [sym_str_lit] = "str_lit",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_SLASH] = "/",
  [anon_sym_STAR] = "*",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_for] = "for",
  [anon_sym_while] = "while",
  [anon_sym_print] = "print",
  [anon_sym_return] = "return",
  [anon_sym_none] = "none",
  [anon_sym_Int] = "Int",
  [anon_sym_String] = "String",
  [anon_sym_Float] = "Float",
  [anon_sym_LPAREN_RPAREN] = "()",
  [anon_sym_extern] = "extern",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_COLON] = ":",
  [anon_sym_struct] = "struct",
  [sym_prog] = "prog",
  [sym__items] = "_items",
  [sym_item] = "item",
  [sym_func_decl] = "func_decl",
  [sym_lit] = "lit",
  [sym_call] = "call",
  [sym_expr] = "expr",
  [sym__exprs] = "_exprs",
  [sym_cond] = "cond",
  [sym_block] = "block",
  [sym_stat] = "stat",
  [sym_stats] = "stats",
  [sym_type] = "type",
  [sym_extern] = "extern",
  [sym__return_type] = "_return_type",
  [sym_func_body] = "func_body",
  [sym__type_specifier] = "_type_specifier",
  [sym_param] = "param",
  [sym_param_list] = "param_list",
  [sym_field] = "field",
  [sym_fields] = "fields",
  [sym_struct_decl] = "struct_decl",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_num_lit] = sym_num_lit,
  [sym_float_lit] = sym_float_lit,
  [sym_str_lit] = sym_str_lit,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_print] = anon_sym_print,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_none] = anon_sym_none,
  [anon_sym_Int] = anon_sym_Int,
  [anon_sym_String] = anon_sym_String,
  [anon_sym_Float] = anon_sym_Float,
  [anon_sym_LPAREN_RPAREN] = anon_sym_LPAREN_RPAREN,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_struct] = anon_sym_struct,
  [sym_prog] = sym_prog,
  [sym__items] = sym__items,
  [sym_item] = sym_item,
  [sym_func_decl] = sym_func_decl,
  [sym_lit] = sym_lit,
  [sym_call] = sym_call,
  [sym_expr] = sym_expr,
  [sym__exprs] = sym__exprs,
  [sym_cond] = sym_cond,
  [sym_block] = sym_block,
  [sym_stat] = sym_stat,
  [sym_stats] = sym_stats,
  [sym_type] = sym_type,
  [sym_extern] = sym_extern,
  [sym__return_type] = sym__return_type,
  [sym_func_body] = sym_func_body,
  [sym__type_specifier] = sym__type_specifier,
  [sym_param] = sym_param,
  [sym_param_list] = sym_param_list,
  [sym_field] = sym_field,
  [sym_fields] = sym_fields,
  [sym_struct_decl] = sym_struct_decl,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_num_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_float_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_str_lit] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_none] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_String] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [sym_prog] = {
    .visible = true,
    .named = true,
  },
  [sym__items] = {
    .visible = false,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_func_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__exprs] = {
    .visible = false,
    .named = true,
  },
  [sym_cond] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_stat] = {
    .visible = true,
    .named = true,
  },
  [sym_stats] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_extern] = {
    .visible = true,
    .named = true,
  },
  [sym__return_type] = {
    .visible = false,
    .named = true,
  },
  [sym_func_body] = {
    .visible = true,
    .named = true,
  },
  [sym__type_specifier] = {
    .visible = false,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_param_list] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_decl] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '!', 10,
        '"', 3,
        '&', 4,
        '(', 15,
        ')', 16,
        '*', 25,
        '+', 21,
        ',', 26,
        '-', 23,
        '/', 24,
        ':', 42,
        ';', 39,
        '<', 29,
        '=', 38,
        '>', 31,
        '{', 35,
        '|', 12,
        '}', 36,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 10,
        '(', 15,
        ')', 16,
        '*', 25,
        '+', 21,
        ',', 26,
        '-', 22,
        '/', 24,
        ';', 39,
        '<', 29,
        '=', 11,
        '>', 31,
        '{', 35,
        '}', 36,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 3,
        '(', 15,
        ')', 16,
        ',', 26,
        '-', 9,
        ':', 42,
        ';', 39,
        '=', 37,
        '{', 35,
        '}', 36,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '!' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '\\' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '&') ADVANCE(34);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '+') ADVANCE(21);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '=') ADVANCE(37);
      if (lookahead == '}') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '(') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == ')') ADVANCE(40);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '0') ADVANCE(8);
      if (lookahead == '>') ADVANCE(41);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead == '|') ADVANCE(33);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_num_lit);
      if (lookahead == '.') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_float_lit);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_str_lit);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_ident);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LPAREN_RPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'F', 1,
        'I', 2,
        'S', 3,
        'e', 4,
        'f', 5,
        'i', 6,
        'l', 7,
        'n', 8,
        'p', 9,
        'r', 10,
        's', 11,
        't', 12,
        'w', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(17);
      if (lookahead == 'x') ADVANCE(18);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(19);
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'f') ADVANCE(22);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(29);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(43);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_Int);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(45);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 35:
      if (lookahead == 's') ADVANCE(48);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(50);
      END_STATE();
    case 40:
      if (lookahead == 'u') ADVANCE(51);
      END_STATE();
    case 41:
      if (lookahead == 'u') ADVANCE(52);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 43:
      if (lookahead == 'l') ADVANCE(54);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 45:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 47:
      if (lookahead == 'r') ADVANCE(57);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_none);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(60);
      END_STATE();
    case 52:
      if (lookahead == 'c') ADVANCE(61);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_Float);
      END_STATE();
    case 56:
      if (lookahead == 'g') ADVANCE(63);
      END_STATE();
    case 57:
      if (lookahead == 'n') ADVANCE(64);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    case 60:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_String);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 6},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 2},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_str_lit] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_none] = ACTIONS(1),
    [anon_sym_Int] = ACTIONS(1),
    [anon_sym_String] = ACTIONS(1),
    [anon_sym_Float] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
  },
  [1] = {
    [sym_prog] = STATE(107),
    [sym__items] = STATE(44),
    [sym_item] = STATE(44),
    [sym_func_decl] = STATE(58),
    [sym_extern] = STATE(68),
    [sym_struct_decl] = STATE(68),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(5),
    [anon_sym_extern] = ACTIONS(7),
    [anon_sym_struct] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(11), 1,
      sym_ident,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_while,
    ACTIONS(31), 1,
      anon_sym_none,
    STATE(3), 1,
      sym_stats,
    STATE(18), 1,
      sym_lit,
    STATE(21), 1,
      sym_call,
    STATE(23), 1,
      sym_stat,
    STATE(52), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(29), 2,
      anon_sym_print,
      anon_sym_return,
  [52] = 15,
    ACTIONS(11), 1,
      sym_ident,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_while,
    ACTIONS(31), 1,
      anon_sym_none,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    STATE(18), 1,
      sym_lit,
    STATE(21), 1,
      sym_call,
    STATE(22), 1,
      sym_stat,
    STATE(55), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(29), 2,
      anon_sym_print,
      anon_sym_return,
  [101] = 3,
    ACTIONS(39), 1,
      anon_sym_else,
    ACTIONS(37), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float_lit,
      sym_str_lit,
      anon_sym_RBRACE,
    ACTIONS(35), 11,
      sym_num_lit,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_let,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      anon_sym_print,
      anon_sym_return,
      anon_sym_none,
  [125] = 2,
    ACTIONS(43), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float_lit,
      sym_str_lit,
      anon_sym_RBRACE,
    ACTIONS(41), 12,
      sym_num_lit,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_let,
      anon_sym_if,
      anon_sym_else,
      anon_sym_for,
      anon_sym_while,
      anon_sym_print,
      anon_sym_return,
      anon_sym_none,
  [147] = 2,
    ACTIONS(47), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float_lit,
      sym_str_lit,
      anon_sym_RBRACE,
    ACTIONS(45), 12,
      sym_num_lit,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_let,
      anon_sym_if,
      anon_sym_else,
      anon_sym_for,
      anon_sym_while,
      anon_sym_print,
      anon_sym_return,
      anon_sym_none,
  [169] = 2,
    ACTIONS(51), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float_lit,
      sym_str_lit,
      anon_sym_RBRACE,
    ACTIONS(49), 11,
      sym_num_lit,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_let,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      anon_sym_print,
      anon_sym_return,
      anon_sym_none,
  [190] = 2,
    ACTIONS(37), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float_lit,
      sym_str_lit,
      anon_sym_RBRACE,
    ACTIONS(35), 11,
      sym_num_lit,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_let,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      anon_sym_print,
      anon_sym_return,
      anon_sym_none,
  [211] = 2,
    ACTIONS(55), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float_lit,
      sym_str_lit,
      anon_sym_RBRACE,
    ACTIONS(53), 11,
      sym_num_lit,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_let,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      anon_sym_print,
      anon_sym_return,
      anon_sym_none,
  [232] = 3,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 13,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [255] = 2,
    ACTIONS(65), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float_lit,
      sym_str_lit,
      anon_sym_RBRACE,
    ACTIONS(63), 11,
      sym_num_lit,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_let,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      anon_sym_print,
      anon_sym_return,
      anon_sym_none,
  [276] = 2,
    ACTIONS(69), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float_lit,
      sym_str_lit,
      anon_sym_RBRACE,
    ACTIONS(67), 11,
      sym_num_lit,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_let,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      anon_sym_print,
      anon_sym_return,
      anon_sym_none,
  [297] = 2,
    ACTIONS(73), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float_lit,
      sym_str_lit,
      anon_sym_RBRACE,
    ACTIONS(71), 11,
      sym_num_lit,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_let,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      anon_sym_print,
      anon_sym_return,
      anon_sym_none,
  [318] = 2,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 13,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [338] = 2,
    ACTIONS(77), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 13,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [358] = 2,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 13,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [378] = 2,
    ACTIONS(81), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(79), 13,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [398] = 2,
    ACTIONS(85), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(83), 13,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [418] = 3,
    ACTIONS(89), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(87), 11,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [440] = 2,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(87), 13,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [460] = 2,
    ACTIONS(85), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(83), 13,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
  [480] = 2,
    ACTIONS(95), 3,
      sym_float_lit,
      sym_str_lit,
      anon_sym_RBRACE,
    ACTIONS(93), 11,
      sym_num_lit,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_let,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      anon_sym_print,
      anon_sym_return,
      anon_sym_none,
  [499] = 2,
    ACTIONS(99), 3,
      sym_float_lit,
      sym_str_lit,
      anon_sym_RBRACE,
    ACTIONS(97), 11,
      sym_num_lit,
      sym_ident,
      anon_sym_true,
      anon_sym_false,
      anon_sym_let,
      anon_sym_if,
      anon_sym_for,
      anon_sym_while,
      anon_sym_print,
      anon_sym_return,
      anon_sym_none,
  [518] = 9,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(101), 1,
      sym_ident,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_lit,
    STATE(21), 1,
      sym_call,
    STATE(33), 1,
      sym_expr,
    STATE(112), 1,
      sym_cond,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [548] = 9,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(101), 1,
      sym_ident,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_lit,
    STATE(21), 1,
      sym_call,
    STATE(33), 1,
      sym_expr,
    STATE(110), 1,
      sym_cond,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [578] = 9,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_while,
    ACTIONS(31), 1,
      anon_sym_none,
    ACTIONS(105), 1,
      sym_ident,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    ACTIONS(29), 2,
      anon_sym_print,
      anon_sym_return,
    STATE(29), 2,
      sym_stat,
      aux_sym_block_repeat1,
  [608] = 9,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(101), 1,
      sym_ident,
    ACTIONS(109), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      sym_lit,
    STATE(21), 1,
      sym_call,
    STATE(48), 1,
      sym_expr,
    STATE(83), 1,
      sym__exprs,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [638] = 9,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(101), 1,
      sym_ident,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_lit,
    STATE(21), 1,
      sym_call,
    STATE(33), 1,
      sym_expr,
    STATE(105), 1,
      sym_cond,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [668] = 9,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_while,
    ACTIONS(31), 1,
      anon_sym_none,
    ACTIONS(105), 1,
      sym_ident,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    ACTIONS(29), 2,
      anon_sym_print,
      anon_sym_return,
    STATE(30), 2,
      sym_stat,
      aux_sym_block_repeat1,
  [698] = 9,
    ACTIONS(113), 1,
      sym_ident,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    ACTIONS(118), 1,
      anon_sym_let,
    ACTIONS(121), 1,
      anon_sym_if,
    ACTIONS(124), 1,
      anon_sym_for,
    ACTIONS(127), 1,
      anon_sym_while,
    ACTIONS(133), 1,
      anon_sym_none,
    ACTIONS(130), 2,
      anon_sym_print,
      anon_sym_return,
    STATE(30), 2,
      sym_stat,
      aux_sym_block_repeat1,
  [728] = 9,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(101), 1,
      sym_ident,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_lit,
    STATE(21), 1,
      sym_call,
    STATE(33), 1,
      sym_expr,
    STATE(88), 1,
      sym_cond,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [758] = 9,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(101), 1,
      sym_ident,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_lit,
    STATE(21), 1,
      sym_call,
    STATE(33), 1,
      sym_expr,
    STATE(121), 1,
      sym_cond,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [788] = 4,
    ACTIONS(89), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(140), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(138), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [807] = 7,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(101), 1,
      sym_ident,
    STATE(18), 1,
      sym_lit,
    STATE(19), 1,
      sym_expr,
    STATE(21), 1,
      sym_call,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [831] = 7,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(101), 1,
      sym_ident,
    STATE(18), 1,
      sym_lit,
    STATE(21), 1,
      sym_call,
    STATE(51), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [855] = 8,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_while,
    ACTIONS(31), 1,
      anon_sym_none,
    ACTIONS(105), 1,
      sym_ident,
    STATE(25), 1,
      sym_stat,
    ACTIONS(29), 2,
      anon_sym_print,
      anon_sym_return,
  [881] = 7,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(101), 1,
      sym_ident,
    STATE(18), 1,
      sym_lit,
    STATE(21), 1,
      sym_call,
    STATE(57), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [905] = 7,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(101), 1,
      sym_ident,
    STATE(18), 1,
      sym_lit,
    STATE(21), 1,
      sym_call,
    STATE(50), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [929] = 8,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_for,
    ACTIONS(27), 1,
      anon_sym_while,
    ACTIONS(31), 1,
      anon_sym_none,
    ACTIONS(105), 1,
      sym_ident,
    STATE(120), 1,
      sym_stat,
    ACTIONS(29), 2,
      anon_sym_print,
      anon_sym_return,
  [955] = 7,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(101), 1,
      sym_ident,
    STATE(18), 1,
      sym_lit,
    STATE(20), 1,
      sym_expr,
    STATE(21), 1,
      sym_call,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [979] = 7,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(101), 1,
      sym_ident,
    STATE(18), 1,
      sym_lit,
    STATE(21), 1,
      sym_call,
    STATE(54), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [1003] = 7,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(101), 1,
      sym_ident,
    STATE(18), 1,
      sym_lit,
    STATE(21), 1,
      sym_call,
    STATE(47), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [1027] = 7,
    ACTIONS(13), 1,
      sym_num_lit,
    ACTIONS(101), 1,
      sym_ident,
    STATE(18), 1,
      sym_lit,
    STATE(21), 1,
      sym_call,
    STATE(45), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float_lit,
      sym_str_lit,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [1051] = 7,
    ACTIONS(5), 1,
      anon_sym_fn,
    ACTIONS(7), 1,
      anon_sym_extern,
    ACTIONS(9), 1,
      anon_sym_struct,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    STATE(58), 1,
      sym_func_decl,
    STATE(72), 1,
      sym_item,
    STATE(68), 2,
      sym_extern,
      sym_struct_decl,
  [1074] = 3,
    ACTIONS(89), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(144), 3,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
  [1088] = 3,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(146), 1,
      anon_sym_EQ,
    ACTIONS(59), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [1102] = 3,
    ACTIONS(89), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(148), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1115] = 3,
    ACTIONS(89), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(150), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1128] = 1,
    ACTIONS(152), 6,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_SEMI,
  [1137] = 3,
    ACTIONS(154), 1,
      anon_sym_SEMI,
    ACTIONS(89), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1149] = 3,
    ACTIONS(156), 1,
      anon_sym_SEMI,
    ACTIONS(89), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1161] = 3,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(89), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1173] = 2,
    STATE(59), 1,
      sym_type,
    ACTIONS(158), 4,
      anon_sym_Int,
      anon_sym_String,
      anon_sym_Float,
      anon_sym_LPAREN_RPAREN,
  [1183] = 3,
    ACTIONS(160), 1,
      anon_sym_SEMI,
    ACTIONS(89), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1195] = 3,
    ACTIONS(162), 1,
      anon_sym_RBRACE,
    ACTIONS(89), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1207] = 2,
    STATE(96), 1,
      sym_type,
    ACTIONS(158), 4,
      anon_sym_Int,
      anon_sym_String,
      anon_sym_Float,
      anon_sym_LPAREN_RPAREN,
  [1217] = 3,
    ACTIONS(164), 1,
      anon_sym_SEMI,
    ACTIONS(89), 2,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1229] = 1,
    ACTIONS(166), 4,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_extern,
      anon_sym_struct,
  [1236] = 1,
    ACTIONS(168), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [1243] = 4,
    ACTIONS(170), 1,
      sym_ident,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      sym_param_list,
    STATE(93), 1,
      sym_param,
  [1256] = 1,
    ACTIONS(174), 4,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_extern,
      anon_sym_struct,
  [1263] = 1,
    ACTIONS(176), 4,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_extern,
      anon_sym_struct,
  [1270] = 1,
    ACTIONS(178), 4,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_extern,
      anon_sym_struct,
  [1277] = 1,
    ACTIONS(180), 4,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_extern,
      anon_sym_struct,
  [1284] = 1,
    ACTIONS(182), 4,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_extern,
      anon_sym_struct,
  [1291] = 4,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
    ACTIONS(186), 1,
      anon_sym_DASH_GT,
    STATE(76), 1,
      sym_func_body,
    STATE(98), 1,
      sym__return_type,
  [1304] = 1,
    ACTIONS(188), 4,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_extern,
      anon_sym_struct,
  [1311] = 1,
    ACTIONS(166), 4,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_extern,
      anon_sym_struct,
  [1318] = 1,
    ACTIONS(190), 4,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_extern,
      anon_sym_struct,
  [1325] = 1,
    ACTIONS(192), 4,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_extern,
      anon_sym_struct,
  [1332] = 1,
    ACTIONS(194), 4,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_extern,
      anon_sym_struct,
  [1339] = 1,
    ACTIONS(196), 4,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_extern,
      anon_sym_struct,
  [1346] = 4,
    ACTIONS(170), 1,
      sym_ident,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      sym_param,
    STATE(94), 1,
      sym_param_list,
  [1359] = 4,
    ACTIONS(200), 1,
      sym_ident,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_fields,
    STATE(89), 1,
      sym_field,
  [1372] = 4,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
    ACTIONS(186), 1,
      anon_sym_DASH_GT,
    STATE(62), 1,
      sym_func_body,
    STATE(91), 1,
      sym__return_type,
  [1385] = 1,
    ACTIONS(204), 4,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_extern,
      anon_sym_struct,
  [1392] = 1,
    ACTIONS(206), 4,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_extern,
      anon_sym_struct,
  [1399] = 3,
    ACTIONS(208), 1,
      anon_sym_EQ,
    ACTIONS(210), 1,
      anon_sym_COLON,
    STATE(116), 1,
      sym__type_specifier,
  [1409] = 3,
    ACTIONS(186), 1,
      anon_sym_DASH_GT,
    ACTIONS(212), 1,
      anon_sym_SEMI,
    STATE(113), 1,
      sym__return_type,
  [1419] = 3,
    ACTIONS(186), 1,
      anon_sym_DASH_GT,
    ACTIONS(214), 1,
      anon_sym_SEMI,
    STATE(118), 1,
      sym__return_type,
  [1429] = 1,
    ACTIONS(216), 3,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
  [1435] = 2,
    ACTIONS(218), 1,
      anon_sym_COMMA,
    ACTIONS(220), 1,
      anon_sym_RBRACE,
  [1442] = 2,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
    ACTIONS(224), 1,
      anon_sym_COMMA,
  [1449] = 2,
    ACTIONS(226), 1,
      anon_sym_RPAREN,
    ACTIONS(228), 1,
      anon_sym_COMMA,
  [1456] = 1,
    ACTIONS(230), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1461] = 2,
    ACTIONS(200), 1,
      sym_ident,
    STATE(87), 1,
      sym_field,
  [1468] = 1,
    ACTIONS(232), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1473] = 2,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    STATE(4), 1,
      sym_block,
  [1480] = 1,
    ACTIONS(236), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1485] = 1,
    ACTIONS(238), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [1490] = 2,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
    STATE(76), 1,
      sym_func_body,
  [1497] = 2,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    STATE(7), 1,
      sym_block,
  [1504] = 1,
    ACTIONS(240), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1509] = 2,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    ACTIONS(242), 1,
      anon_sym_RPAREN,
  [1516] = 2,
    ACTIONS(210), 1,
      anon_sym_COLON,
    STATE(97), 1,
      sym__type_specifier,
  [1523] = 1,
    ACTIONS(244), 2,
      anon_sym_LBRACE,
      anon_sym_SEMI,
  [1528] = 1,
    ACTIONS(246), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1533] = 2,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_func_body,
  [1540] = 2,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      sym_block,
  [1547] = 2,
    ACTIONS(210), 1,
      anon_sym_COLON,
    STATE(85), 1,
      sym__type_specifier,
  [1554] = 1,
    ACTIONS(248), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1559] = 2,
    ACTIONS(170), 1,
      sym_ident,
    STATE(101), 1,
      sym_param,
  [1566] = 1,
    ACTIONS(250), 1,
      anon_sym_LPAREN,
  [1570] = 1,
    ACTIONS(252), 1,
      anon_sym_LBRACE,
  [1574] = 1,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
  [1578] = 1,
    ACTIONS(256), 1,
      anon_sym_SEMI,
  [1582] = 1,
    ACTIONS(258), 1,
      ts_builtin_sym_end,
  [1586] = 1,
    ACTIONS(146), 1,
      anon_sym_EQ,
  [1590] = 1,
    ACTIONS(260), 1,
      anon_sym_fn,
  [1594] = 1,
    ACTIONS(262), 1,
      anon_sym_SEMI,
  [1598] = 1,
    ACTIONS(264), 1,
      anon_sym_LPAREN,
  [1602] = 1,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
  [1606] = 1,
    ACTIONS(268), 1,
      anon_sym_SEMI,
  [1610] = 1,
    ACTIONS(270), 1,
      anon_sym_LPAREN,
  [1614] = 1,
    ACTIONS(272), 1,
      anon_sym_LPAREN,
  [1618] = 1,
    ACTIONS(274), 1,
      anon_sym_EQ,
  [1622] = 1,
    ACTIONS(276), 1,
      sym_ident,
  [1626] = 1,
    ACTIONS(212), 1,
      anon_sym_SEMI,
  [1630] = 1,
    ACTIONS(278), 1,
      sym_ident,
  [1634] = 1,
    ACTIONS(280), 1,
      anon_sym_RPAREN,
  [1638] = 1,
    ACTIONS(282), 1,
      anon_sym_RPAREN,
  [1642] = 1,
    ACTIONS(284), 1,
      sym_ident,
  [1646] = 1,
    ACTIONS(286), 1,
      sym_ident,
  [1650] = 1,
    ACTIONS(288), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 52,
  [SMALL_STATE(4)] = 101,
  [SMALL_STATE(5)] = 125,
  [SMALL_STATE(6)] = 147,
  [SMALL_STATE(7)] = 169,
  [SMALL_STATE(8)] = 190,
  [SMALL_STATE(9)] = 211,
  [SMALL_STATE(10)] = 232,
  [SMALL_STATE(11)] = 255,
  [SMALL_STATE(12)] = 276,
  [SMALL_STATE(13)] = 297,
  [SMALL_STATE(14)] = 318,
  [SMALL_STATE(15)] = 338,
  [SMALL_STATE(16)] = 358,
  [SMALL_STATE(17)] = 378,
  [SMALL_STATE(18)] = 398,
  [SMALL_STATE(19)] = 418,
  [SMALL_STATE(20)] = 440,
  [SMALL_STATE(21)] = 460,
  [SMALL_STATE(22)] = 480,
  [SMALL_STATE(23)] = 499,
  [SMALL_STATE(24)] = 518,
  [SMALL_STATE(25)] = 548,
  [SMALL_STATE(26)] = 578,
  [SMALL_STATE(27)] = 608,
  [SMALL_STATE(28)] = 638,
  [SMALL_STATE(29)] = 668,
  [SMALL_STATE(30)] = 698,
  [SMALL_STATE(31)] = 728,
  [SMALL_STATE(32)] = 758,
  [SMALL_STATE(33)] = 788,
  [SMALL_STATE(34)] = 807,
  [SMALL_STATE(35)] = 831,
  [SMALL_STATE(36)] = 855,
  [SMALL_STATE(37)] = 881,
  [SMALL_STATE(38)] = 905,
  [SMALL_STATE(39)] = 929,
  [SMALL_STATE(40)] = 955,
  [SMALL_STATE(41)] = 979,
  [SMALL_STATE(42)] = 1003,
  [SMALL_STATE(43)] = 1027,
  [SMALL_STATE(44)] = 1051,
  [SMALL_STATE(45)] = 1074,
  [SMALL_STATE(46)] = 1088,
  [SMALL_STATE(47)] = 1102,
  [SMALL_STATE(48)] = 1115,
  [SMALL_STATE(49)] = 1128,
  [SMALL_STATE(50)] = 1137,
  [SMALL_STATE(51)] = 1149,
  [SMALL_STATE(52)] = 1161,
  [SMALL_STATE(53)] = 1173,
  [SMALL_STATE(54)] = 1183,
  [SMALL_STATE(55)] = 1195,
  [SMALL_STATE(56)] = 1207,
  [SMALL_STATE(57)] = 1217,
  [SMALL_STATE(58)] = 1229,
  [SMALL_STATE(59)] = 1236,
  [SMALL_STATE(60)] = 1243,
  [SMALL_STATE(61)] = 1256,
  [SMALL_STATE(62)] = 1263,
  [SMALL_STATE(63)] = 1270,
  [SMALL_STATE(64)] = 1277,
  [SMALL_STATE(65)] = 1284,
  [SMALL_STATE(66)] = 1291,
  [SMALL_STATE(67)] = 1304,
  [SMALL_STATE(68)] = 1311,
  [SMALL_STATE(69)] = 1318,
  [SMALL_STATE(70)] = 1325,
  [SMALL_STATE(71)] = 1332,
  [SMALL_STATE(72)] = 1339,
  [SMALL_STATE(73)] = 1346,
  [SMALL_STATE(74)] = 1359,
  [SMALL_STATE(75)] = 1372,
  [SMALL_STATE(76)] = 1385,
  [SMALL_STATE(77)] = 1392,
  [SMALL_STATE(78)] = 1399,
  [SMALL_STATE(79)] = 1409,
  [SMALL_STATE(80)] = 1419,
  [SMALL_STATE(81)] = 1429,
  [SMALL_STATE(82)] = 1435,
  [SMALL_STATE(83)] = 1442,
  [SMALL_STATE(84)] = 1449,
  [SMALL_STATE(85)] = 1456,
  [SMALL_STATE(86)] = 1461,
  [SMALL_STATE(87)] = 1468,
  [SMALL_STATE(88)] = 1473,
  [SMALL_STATE(89)] = 1480,
  [SMALL_STATE(90)] = 1485,
  [SMALL_STATE(91)] = 1490,
  [SMALL_STATE(92)] = 1497,
  [SMALL_STATE(93)] = 1504,
  [SMALL_STATE(94)] = 1509,
  [SMALL_STATE(95)] = 1516,
  [SMALL_STATE(96)] = 1523,
  [SMALL_STATE(97)] = 1528,
  [SMALL_STATE(98)] = 1533,
  [SMALL_STATE(99)] = 1540,
  [SMALL_STATE(100)] = 1547,
  [SMALL_STATE(101)] = 1554,
  [SMALL_STATE(102)] = 1559,
  [SMALL_STATE(103)] = 1566,
  [SMALL_STATE(104)] = 1570,
  [SMALL_STATE(105)] = 1574,
  [SMALL_STATE(106)] = 1578,
  [SMALL_STATE(107)] = 1582,
  [SMALL_STATE(108)] = 1586,
  [SMALL_STATE(109)] = 1590,
  [SMALL_STATE(110)] = 1594,
  [SMALL_STATE(111)] = 1598,
  [SMALL_STATE(112)] = 1602,
  [SMALL_STATE(113)] = 1606,
  [SMALL_STATE(114)] = 1610,
  [SMALL_STATE(115)] = 1614,
  [SMALL_STATE(116)] = 1618,
  [SMALL_STATE(117)] = 1622,
  [SMALL_STATE(118)] = 1626,
  [SMALL_STATE(119)] = 1630,
  [SMALL_STATE(120)] = 1634,
  [SMALL_STATE(121)] = 1638,
  [SMALL_STATE(122)] = 1642,
  [SMALL_STATE(123)] = 1646,
  [SMALL_STATE(124)] = 1650,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prog, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stat, 3, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stat, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stat, 5, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stat, 5, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stat, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stat, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lit, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lit, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stat, 8, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stat, 8, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stat, 6, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stat, 6, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stat, 4, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stat, 4, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stats, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stats, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stats, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stats, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [121] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [124] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(124),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prog, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cond, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exprs, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exprs, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_specifier, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 4, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_decl, 5, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_body, 3, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_decl, 7, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern, 7, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 5, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_body, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_body, 4, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern, 8, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__items, 2, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_decl, 6, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern, 6, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cond, 7, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 2, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 3, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 1, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 1, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__return_type, 2, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 2, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 3, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [258] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_wng(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
